version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: hafsa
      RABBITMQ_DEFAULT_PASS: 123456

  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  notification_service:
    build:
      context: ./API_Notification
    ports:
      - '3001:3001'
    environment:
      - RABBITMQ_URL=amqp://hafsa:123456@rabbitmq:5672
      - MONGO_URL=mongodb://mongodb:27017/Notifications
      - SMTP_HOST=hafsa@gmail.com
      - SMTP_PORT=587
      - SMTP_USER=zian@gmail.com
      - SMTP_PASS=**hafsa1996@
    depends_on:
      - rabbitmq
      - mongodb

  livre_service:
    build:
      context: ./API_Livre
    ports:
      - '3000:3000'
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
      - MONGO_URL=mongodb://mongodb:27017/dblivre
    depends_on:
      - rabbitmq
      - mongodb
gateway:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - notification_service
      - livre_service
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
